name: fakahany
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.3.3
  dartz: ^0.10.1
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  dots_indicator: ^3.0.0
  flutter_localization: ^0.2.2
  flutter_svg: ^2.0.14
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fruits.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
       - asset: assets/fonts/Cairo-Medium.ttf
         weight: 500
       - asset: assets/fonts/Cairo-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Cairo-Bold.ttf
         weight: 700


flutter_assets_generator:
  output_dir: generated
  auto_detection: true
  class_name: Assets
flutter_intl:
  enabled: true
